name       : font-freefont-ttf
version    : 5.3.12
release    : 1
source     :
    - http://ftp.gnu.org/gnu/freefont/freefont-ttf-20120503.zip : 7c85baf1bf82a1a1845d1322112bc6ca982221b484e3b3925022e25b5cae89af
license    : GPL-3.0-or-later
component  : desktop.font
summary    : GNU FreeFont is a free family of scalable outline fonts, suitable for general use on computers and for desktop publishing. It is Unicode-encoded for compatibility with all modern operating systems.
description: |
    GNU FreeFont is a free family of scalable outline fonts, suitable for general use on computers and for desktop publishing. It is Unicode-encoded for compatibility with all modern operating systems.
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/freefont/
    install -dm644 $fontdir
    cp -R $workdir/*.ttf $fontdir
